kind = "web"
previewPath = "/"
title = "Hostel Management"
version = "1.0.0"
id = "artifacts/hostel-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23408

[services.development]
run = "pnpm --filter @workspace/hostel-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hostel-app", "run", "build" ]
publicDir = "artifacts/hostel-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23408"
BASE_PATH = "/"
